version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    working_dir: /app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/lib/:/var/lib/mysql
      - ./docker/mysql/dump/:/var/local
    environment:
      MYSQL_ROOT_PASSWORD: root
